<a href="https://colab.research.google.com/github/JavierTrc/numpy-pandas-exercices/blob/master/Numpy_Excercises_Session_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

# Numpy Excercises - Session 2

### Exercise 1

Reshape `array1` to 7x3 dimensions.

In [3]:
array1 = np.arange(0, 21)
array1 = array1.reshape((7,3))
array1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

### Exercise 2

Reshape `array2` into a 3D array of 3x3x3 dimensions.

In [4]:
array2 = np.arange(0, 27).reshape(9, 3)
array2 =  array2.reshape((3,3,3))
array2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

### Exercise 3: Reshape vs Resize

reshape and resize both do the same thin. So, what's the difference?

Follow the instructions and find out.


In [5]:
# Run this cell without changing the code.
array3 = np.arange(0, 9)

array3.reshape((3, 3))
print(array3)

array3.resize((3, 3))
print(array3)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# Question: What is the difference between reshape and resize

a = "resize returns a new copy of the array, while reshape changes the original array"
b = "reshape returns a new copy of the array, while resize changes the original array"
c = "both resize and reshape works in the same way with the original array"
b

'reshape returns a new copy of the array, while resize changes the original array'

### Exercise 4

Concatenate arrays `a`, `b`, and `c`.

In [9]:
a = np.arange(0, 3)
b = np.arange(3, 6)
c = np.arange(6, 9)
array4 = np.concatenate((a,b,c))
array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### Exercise 5

Concatenate arrays `m1` and `m2` vertically.

In [10]:
m1 = np.array(
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8]
    ]
)

m2 = np.array(
    [
      [9, 10, 11, 12],
      [13, 14, 15, 16]
    ]
)

array5 = np.vstack((m1,m2))
array5

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Exercise 6

Concatenate arrays `m1` and `m2` horizontally.

In [12]:
m1 = np.array(
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8]
    ]
)

m2 = np.array(
    [
      [9, 10, 11, 12],
      [13, 14, 15, 16]
    ]
)

array6 = np.hstack((m1,m2))
array6

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

### Exercise 7

Get all the cells with value equals to `0` as a list of tuples.


In [18]:
matrix = np.array([
    [1, 4, 7, 5, 0],
    [0, 2, 9, 0, 1],
    [3, 6, 0, 5, 3],
    [7, 3, 0, 1, 0],
    [3, 6, 1, 0, 4]
])

array7 = np.where(a == 0)
array7[0][0]

0

### Exercise 8

Check the documentation for `np.diag` and `np.fliplr`. Use them to extract the diagonals arrays for `matrix`.



In [20]:
diag1 = np.diag(matrix)
diag2 = np.diag(np.fliplr(matrix))
diag1
# diag2

array([1, 2, 0, 1, 4])

### Exercise 9

Get the values of the 3th column in `matrix` and the values for the 2th row in `matrix`. Both as numpy arrays.


In [21]:

column = matrix[:, 3 - 1]
row = matrix[2 -1, :]
print(column)
print(row)

[7 9 0 0 1]
[0 2 9 0 1]


## Exercise 10

Create a new matrix ***x*** from ***a*** and ***m*** with the folowing structure:



```
array([[4, 4, 5, 4, 4],
       [4, 4, 5, 4, 4],
       [4, 4, 5, 4, 4]])
```



In [28]:
a = np.full((3, 1), 5)
m = np.full((3, 4), 4)

x = np.hstack((m[:,:2], a, m[:,2:]))
# x = np.insert(m, 2, 5, axis=1)
x

[[4 4]
 [4 4]
 [4 4]]


array([[4, 4, 5, 4, 4],
       [4, 4, 5, 4, 4],
       [4, 4, 5, 4, 4]])

## Exercise 11

Given a:

```
a = array([[1],
       [1],
       [2],
       [4]])
```

Create a new array **b** with the following structure:

```
np.array([
  [1, 0, 0],
  [1, 0, 0],
  [0, 1, 0],
  [0, 0, 1],
])
```
Do you detect the pattern? Which operation do you need to create this structure.?




In [ ]:
# one hot encode excersise for numpy 

# Challenge, Tic Tac Toe


In [49]:
cell = {
    0: ' ',
    1: 'X',
    2: 'O'
}

def print_board():
  print('-------------')
  print(f'| {cell[game[0][0]]} | {cell[game[0][1]]} | {cell[game[0][2]]} |')
  print('-------------')
  print(f'| {cell[game[1][0]]} | {cell[game[1][1]]} | {cell[game[1][2]]} |')
  print('-------------')
  print(f'| {cell[game[2][0]]} | {cell[game[2][1]]} | {cell[game[2][2]]} |')
  print('-------------')

def skynet_move():
  # Select a random empty cell in `game` array and set with value `2`.
  # If no empty cells available, do nothing.
  free_indices = np.where(game == 0)
  if free_indices[0].size != 0:
    index = np.random.randint(free_indices[0].size)
    game[free_indices[0][index]][free_indices[1][index]] = 2
  pass

def win_move(player, r, c):
  # Check if the player's move is a win move.
  # A win move meets one of these conditions:
  #   - All values at row `r` are equal to `player`.
  #   - All values at column `c` are equal to `player`.
  #   - All values at main diagonal ((0, 0) to (2, 2)) are equal to  `player`.
  #   - All values at second diagonal ((2, 0) to (0, 2)) are equal to  `player`.
  # Return True if one of the conditions are met, False otherwise.
  if np.all(game[r] == player):
    return True
  elif np.all(game[c] == player):
    return True
  elif np.all(np.diag(game) == player):
    return True
  elif np.all(np.diag(np.fliplr(game)) == player):
    return True
  else:
    return False


def human_move(r, c):
  # Set value `1` at game[r][c] if the cell if empty and return True.
  # If cell is not empty print "Cell is not empty" and return False.
  if game[r][c] == 0:
    game[r][c] = 1
    return True
  else:
    print('Cell is not empty')
    return False

def winner_exists():
  # If one of the players has already won the game, return True.
  # Return False otherwise.
  if win_move(1,0,0) or win_move(2,0,0):
    return True
  elif  win_move(1,1,1) or win_move(2,1,1):
    return True
  elif  win_move(1,2,2) or win_move(2,2,2):
    return True
  else:
    return False 

def is_game_on():
  # This method checks the current status of the game.
  # A game is on if meets one of two conditios:
  #  - There is still available cells.
  #  - There is still no winners.
  if np.where(game == 0)[0].size == 0:
    return False
  else:
    return not winner_exists()  

In [37]:
# Run this cell to restart the game.

# Create a 3x3 array with zero values.
game = np.zeros((3,3))

In [50]:
#@title Tic tac toe controls
#@markdown Select the cell for your next move!.
row_value = "0" #@param ["0", "1", "2"] 
column_value = "0" #@param ["0", "1", "2"]

row = int(row_value)
column = int(column_value)
if(is_game_on()):
  status = human_move(row, column)
  if(win_move(1, row, column)):
    print('Human wins')
  elif(status):
    skynet_move()
    if(win_move(2, row, column)):
      print('Skynet wins')
else:
  print('Game over.')
  
print_board()

Game over.
-------------
| X | O | X |
-------------
| X | O | O |
-------------
| O | X | X |
-------------


# Challenge: Basic data analysis

The following numpy array is taken from the a census dataset. Every column in this matrix contains some demografic information. For this exercise You will focus in the following columns:

*   Column[0]: Age
*   Column[1]: workclass
*   Column[3]: education
*   Column[5]: marital-status
*   Column[9]: sex
*   Column[10]: capital-gain

Please find the following information:


*   Age average
*   Types of workclass, education and marital-status
*   How many records are for male
*   How many records are for female
*   How many females are above age of 30
*   Avergage of capital-gain for males
*   Avergage of capital-gain for females







In [63]:
# First upload file "census.npy" befor running this cell.
with open('census.npy', 'rb') as f:
  census_data = np.load(f, allow_pickle=True)
census_data[:10,:]

array([[50, ' Self-emp-not-inc', 83311, ' Bachelors', 13,
        ' Married-civ-spouse', ' Exec-managerial', ' Husband', ' White',
        ' Male', 0, 0, 13, ' United-States', ' <=50K'],
       [38, ' Private', 215646, ' HS-grad', 9, ' Divorced',
        ' Handlers-cleaners', ' Not-in-family', ' White', ' Male', 0, 0,
        40, ' United-States', ' <=50K'],
       [53, ' Private', 234721, ' 11th', 7, ' Married-civ-spouse',
        ' Handlers-cleaners', ' Husband', ' Black', ' Male', 0, 0, 40,
        ' United-States', ' <=50K'],
       [28, ' Private', 338409, ' Bachelors', 13, ' Married-civ-spouse',
        ' Prof-specialty', ' Wife', ' Black', ' Female', 0, 0, 40,
        ' Cuba', ' <=50K'],
       [37, ' Private', 284582, ' Masters', 14, ' Married-civ-spouse',
        ' Exec-managerial', ' Wife', ' White', ' Female', 0, 0, 40,
        ' United-States', ' <=50K'],
       [49, ' Private', 160187, ' 9th', 5, ' Married-spouse-absent',
        ' Other-service', ' Not-in-family', ' Black

In [96]:
# Average age
average = np.average(census_data[:,0].astype(np.int))
print(average)

# Types of workclass, education, marital-status
workclasses = np.unique(census_data[:,1].astype(np.str))
print(workclasses)

educations = np.unique(census_data[:,3].astype(np.str))
print(educations)

marital_statuses = np.unique(census_data[:,5].astype(np.str))
print(marital_statuses)

np.unique(census_data[:,9].astype(np.str))

38.581633906633904
[' ?' ' Federal-gov' ' Local-gov' ' Never-worked' ' Private'
 ' Self-emp-inc' ' Self-emp-not-inc' ' State-gov' ' Without-pay']
[' 10th' ' 11th' ' 12th' ' 1st-4th' ' 5th-6th' ' 7th-8th' ' 9th'
 ' Assoc-acdm' ' Assoc-voc' ' Bachelors' ' Doctorate' ' HS-grad'
 ' Masters' ' Preschool' ' Prof-school' ' Some-college']
[' Divorced' ' Married-AF-spouse' ' Married-civ-spouse'
 ' Married-spouse-absent' ' Never-married' ' Separated' ' Widowed']


array([' Female', ' Male'], dtype='<U7')

In [97]:
# Female Records
mask = census_data[:,9] == ' Female'

females = census_data[mask]
print(females.shape)

(10771, 15)


In [98]:
# Male Records
mask = census_data[:,9] == ' Male'

males = census_data[mask]
print(males.shape)

print(females.shape[0] + males.shape[0])

(21789, 15)
32560


In [105]:
females_over_30 = females[females[:,0] > 30]
print(females_over_30.shape)

(6512, 15)


In [109]:
np.average(males[:,10].astype(np.int))

1329.3313139657625

In [110]:
np.average(females[:,10].astype(np.int))

568.4105468387336